// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "API root",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "API v1 root",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List cars",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Get car",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/analytics/activity": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Activity analytics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/analytics/regeneration": {
            "get": {
                "description": "Returns estimated regeneration metrics. Meta flags when values are estimated from available drive/position data.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Regeneration analytics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/battery-health": {
            "get": {
                "description": "Original compatible battery-health endpoint. Use ` + "`" + `/v1/cars/{CarID}/charts/battery/health` + "`" + ` for chart-friendly series.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Battery health",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/calendar/charges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge calendar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Calendar year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Calendar month",
                        "name": "month",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/calendar/drives": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive calendar",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Calendar year",
                        "name": "year",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Calendar month",
                        "name": "month",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List charges",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges/current": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Current charge",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges/{ChargeID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Charge details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Charge ID",
                        "name": "ChargeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges/{ChargeID}/details": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge details context",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Charge ID",
                        "name": "ChargeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/battery/health": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Battery health chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/battery/range": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Battery range chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/cost": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge cost chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/efficiency": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge efficiency chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/energy": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge energy chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/location": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge location chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Location bucket count",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/power": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge power chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/charges/soc": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Charge SOC distribution chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/drives/distance": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive distance chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start; defaults to the last 365 days",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end; defaults to now",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/drives/efficiency": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive efficiency chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/drives/energy": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive energy chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/drives/speed": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive speed chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/drives/temperature": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive temperature chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/mileage": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Mileage chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/overview": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Overview charts",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start; defaults to the last 30 days",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end; defaults to now",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/states/duration": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "State duration chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charts/vampire-drain": {
            "get": {
                "description": "Returns an explicit empty structure when TeslaMate schema does not allow a reliable vampire-drain calculation.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Vampire drain chart",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIChartResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/command": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List command options",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/command/{Command}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Execute command",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "Command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/drives": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List drives",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum drive distance",
                        "name": "minDistance",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum drive distance",
                        "name": "maxDistance",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/drives/{DriveID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Drive details",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "DriveID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/drives/{DriveID}/details": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Drive details context",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "DriveID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/insights": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Insights summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/insights/events": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Insight events",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Comma-separated insight types",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/logging": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Get logging status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/logging/{Command}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Update logging status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Logging command",
                        "name": "Command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/map/visited": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Visited map",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start; defaults to the last 90 days",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end; defaults to now",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/statistics": {
            "get": {
                "description": "TeslaMate Statistics dashboard aligned aggregate response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Statistics dashboard summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Current vehicle status",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/summary": {
            "get": {
                "description": "New summary endpoint for third-party apps. Returns drive, charge, parking, efficiency, cost, mileage, state snapshot, and vampire-drain availability in one payload.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Summary overview",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, offset values, decoded-space offsets, local datetime, or date-only. Encode + as %2B in URLs when possible.",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "RFC3339, offset values, decoded-space offsets, local datetime, or date-only. Date-only endDate is expanded to local end-of-day.",
                        "name": "endDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIObjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/timeline": {
            "get": {
                "description": "Returns drives, charges, states, and updates in one timeline ordered by time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Unified timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Date range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Date range end",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "startDate|type",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "asc|desc",
                        "name": "order",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.APIListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/updates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List updates",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/wake_up": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Wake up vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/globalsettings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Global settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.APIChartPoint": {
            "type": "object",
            "properties": {
                "label": {
                    "type": "string"
                },
                "time": {
                    "type": "string"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "main.APIChartResponse": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "car_id": {
                    "type": "integer"
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "range": {
                    "$ref": "#/definitions/main.APIRange"
                },
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.APIChartSeries"
                    }
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "main.APIChartSeries": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "points": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.APIChartPoint"
                    }
                },
                "unit": {
                    "type": "string"
                }
            }
        },
        "main.APIErrorDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.APIErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/main.APIErrorDetail"
                }
            }
        },
        "main.APIListResponse": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "data": {
                    "type": "array",
                    "items": {}
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "pagination": {
                    "$ref": "#/definitions/main.APIPagination"
                },
                "range": {
                    "$ref": "#/definitions/main.APIRange"
                },
                "timezone": {
                    "type": "string"
                }
            }
        },
        "main.APIObjectResponse": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "data": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "meta": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "range": {
                    "$ref": "#/definitions/main.APIRange"
                },
                "timezone": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/main.APIUnits"
                }
            }
        },
        "main.APIPagination": {
            "type": "object",
            "properties": {
                "page": {
                    "type": "integer"
                },
                "show": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "main.APIRange": {
            "type": "object",
            "properties": {
                "end": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                }
            }
        },
        "main.APIUnits": {
            "type": "object",
            "properties": {
                "consumption": {
                    "type": "string"
                },
                "currency": {
                    "type": "string"
                },
                "distance": {
                    "type": "string"
                },
                "duration": {
                    "type": "string"
                },
                "energy": {
                    "type": "string"
                },
                "percentage": {
                    "type": "string"
                },
                "speed": {
                    "type": "string"
                },
                "temperature": {
                    "type": "string"
                }
            }
        },
        "main.SwaggerDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "main.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Unable to load summary."
                }
            }
        },
        "main.SwaggerMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                },
                "path": {
                    "type": "string",
                    "example": "/api/v1"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "TeslaMateApi",
	Description:      "RESTful API for TeslaMate-backed vehicle, charge, drive, statistics, chart, timeline, and insight data. Original TeslaMateApi routes remain compatible; redesigned extension routes may introduce breaking changes. Date query parameters support RFC3339, timezone offsets, decoded-space offsets, local datetime, and date-only formats. When using `+08:00` in URLs, prefer `%2B08:00`, though decoded-space offsets are also accepted.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
