// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "API root",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/healthz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Ping",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/readyz": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "Readiness check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    },
                    "503": {
                        "description": "Service Unavailable",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "System"
                ],
                "summary": "API v1 root",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerMessageResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List cars",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Get car",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/battery-health": {
            "get": {
                "description": "Original compatible battery-health endpoint. Use ` + "`" + `/v1/cars/{CarID}/charts/battery/health` + "`" + ` for chart-friendly series.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Battery health",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/calendar": {
            "get": {
                "description": "Unified calendar endpoint for drives/charges metrics. Supports day, week, month buckets and returns summary + item list.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Calendar",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "day|week|month",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List charges",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size alias",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset alias",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date|-start_date|duration|-duration|cost|-cost|energy|-energy",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "summary,location,energy,cost",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges/current": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Current charge",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/charges/{ChargeID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Charge details",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Charge ID",
                        "name": "ChargeID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/command": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List command options",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/command/{Command}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Execute command",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Command name",
                        "name": "Command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/dashboard": {
            "get": {
                "description": "Aggregated dashboard payload for app home. Returns statistics, calendar summary, optional series/distribution placeholders, and warnings in one request.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Dashboard",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "year|month|week|custom",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD or RFC3339",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "custom range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "custom range end",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/distributions": {
            "get": {
                "description": "Distribution buckets for drive and charge behavior. Supports hour, duration, distance, speed, energy and power distributions.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Distributions",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "comma separated metrics: drive_start_hour,drive_duration,drive_distance,drive_speed,charge_start_hour,charge_duration,charge_energy,charge_power",
                        "name": "metrics",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/drives": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List drives",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Supports RFC3339, offset values, decoded-space offsets, local datetime, and date-only values",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Minimum drive distance",
                        "name": "minDistance",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "Maximum drive distance",
                        "name": "maxDistance",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size alias",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Offset alias",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "start_date|-start_date|distance|-distance|duration|-duration|efficiency|-efficiency",
                        "name": "sort",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "summary,locations,energy",
                        "name": "include",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/drives/{DriveID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Drive details",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Drive ID",
                        "name": "DriveID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/insights": {
            "get": {
                "description": "Baseline-comparison insights generated from current range versus previous equivalent range, including efficiency, cost, charging, battery and anomaly signals.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Insights",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "comma separated types: efficiency,cost,charging,driving,battery,anomaly",
                        "name": "types",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "insight count limit, 1-100, default 20",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/logging": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Get logging status",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/logging/{Command}": {
            "put": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Update logging status",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Logging command",
                        "name": "Command",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/map/visited": {
            "get": {
                "description": "Visited geo points and map bounds for heatmap/coverage rendering.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Visited map",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/series": {
            "get": {
                "description": "Unified time series endpoint with scope-aware metrics and chart metadata. Unsupported metric/scope pairs are skipped with warnings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Series",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "drives|charges|battery|states|overview",
                        "name": "scope",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "comma separated metrics: distance,efficiency,speed,energy,cost,power,soc,range,regeneration,vampire_drain",
                        "name": "metrics",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "raw|hour|day|week|month|year",
                        "name": "bucket",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/statistics": {
            "get": {
                "description": "Unified period statistics with explicit overview/drive/charge/battery sections, including efficiency, cost, energy and parking metrics.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Statistics",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "year|month|week|custom",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "YYYY-MM-DD or RFC3339",
                        "name": "date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "custom range start",
                        "name": "startDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "custom range end",
                        "name": "endDate",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ObjectEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/status": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Current vehicle status",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/timeline": {
            "get": {
                "description": "Unified timeline feed for drive/charge/state activities with pagination.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Extended API"
                ],
                "summary": "Timeline",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range start",
                        "name": "startDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "range end",
                        "name": "endDate",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "page size",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "offset",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.v1ListEnvelope"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.v1ErrorEnvelope"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/updates": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "List updates",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Page number",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page size",
                        "name": "show",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/cars/{CarID}/wake_up": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Wake up vehicle",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        },
        "/v1/globalsettings": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Compatible API"
                ],
                "summary": "Global settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.SwaggerErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.SwaggerDataResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "object",
                    "additionalProperties": true
                }
            }
        },
        "main.SwaggerErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "Unable to load summary."
                }
            }
        },
        "main.SwaggerMessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "example": "pong"
                },
                "path": {
                    "type": "string",
                    "example": "/api/v1"
                }
            }
        },
        "main.v1Error": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "main.v1ErrorEnvelope": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/main.v1Error"
                }
            }
        },
        "main.v1ListEnvelope": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/main.v1Meta"
                },
                "pagination": {
                    "$ref": "#/definitions/main.v1Pagination"
                },
                "warnings": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "main.v1Meta": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "generated_at": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "unit": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "main.v1ObjectEnvelope": {
            "type": "object",
            "properties": {
                "data": {},
                "meta": {
                    "$ref": "#/definitions/main.v1Meta"
                },
                "warnings": {
                    "type": "array",
                    "items": {}
                }
            }
        },
        "main.v1Pagination": {
            "type": "object",
            "properties": {
                "limit": {
                    "type": "integer"
                },
                "offset": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{"http", "https"},
	Title:            "TeslaMateApi",
	Description:      "RESTful API for TeslaMate-backed vehicle, charge, drive, statistics, chart, timeline, and insight data. Original TeslaMateApi routes remain compatible; redesigned extension routes may introduce breaking changes. Date query parameters support RFC3339, timezone offsets, decoded-space offsets, local datetime, and date-only formats. When using `+08:00` in URLs, prefer `%2B08:00`, though decoded-space offsets are also accepted.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
