// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/v2": {
            "get": {
                "description": "Returns the V2 analytics API version, scope, and currently advertised feature groups.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Summary"
                ],
                "summary": "V2 API capability information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2InfoAPIResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/cars/{CarID}/analytics/driving": {
            "get": {
                "description": "Returns objective driving statistics and optional previous-period comparison for one car.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Driving Analytics"
                ],
                "summary": "V2 driving analytics summary",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "quarter",
                            "year",
                            "custom",
                            "lifetime"
                        ],
                        "type": "string",
                        "description": "Aggregation period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start datetime in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End datetime in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "none",
                            "previous_period",
                            "previous_year",
                            "lifetime_average"
                        ],
                        "type": "string",
                        "description": "Comparison mode",
                        "name": "compare",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2DrivingAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/cars/{CarID}/analytics/driving/distribution": {
            "get": {
                "description": "Returns drive-count, distance, and duration distribution for a selected factual dimension.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Driving Analytics"
                ],
                "summary": "V2 driving analytics distribution",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "quarter",
                            "year",
                            "custom",
                            "lifetime"
                        ],
                        "type": "string",
                        "description": "Aggregation period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start datetime in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End datetime in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "hour_of_day",
                            "day_of_week",
                            "distance_bucket",
                            "duration_bucket",
                            "speed_bucket",
                            "consumption_bucket",
                            "temperature_bucket"
                        ],
                        "type": "string",
                        "description": "Distribution dimension",
                        "name": "dimension",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2DrivingDistributionAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/cars/{CarID}/analytics/driving/ranking": {
            "get": {
                "description": "Returns objective top drives or top driving days by selected ranking type.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Driving Analytics"
                ],
                "summary": "V2 driving analytics ranking",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "quarter",
                            "year",
                            "custom",
                            "lifetime"
                        ],
                        "type": "string",
                        "description": "Aggregation period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start datetime in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End datetime in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "longest_distance",
                            "longest_duration",
                            "highest_speed",
                            "lowest_consumption",
                            "highest_consumption",
                            "highest_distance_day"
                        ],
                        "type": "string",
                        "description": "Ranking type",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Result limit from 1 to 100",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2DrivingRankingAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/cars/{CarID}/analytics/driving/timeseries": {
            "get": {
                "description": "Returns driving metrics grouped by day, week, month, or year for charting.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Driving Analytics"
                ],
                "summary": "V2 driving analytics timeseries",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "quarter",
                            "year",
                            "custom",
                            "lifetime"
                        ],
                        "type": "string",
                        "description": "Aggregation period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start datetime in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End datetime in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "year"
                        ],
                        "type": "string",
                        "description": "Timeseries grouping",
                        "name": "group_by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2DrivingTimeseriesAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        },
        "/v2/cars/{CarID}/analytics/summary": {
            "get": {
                "description": "Returns objective driving, charging, parking, battery, update, and charging-cost summary metrics for one car in a selected period.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "V2 Summary"
                ],
                "summary": "V2 period summary analytics",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Car ID",
                        "name": "CarID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "enum": [
                            "day",
                            "week",
                            "month",
                            "quarter",
                            "year",
                            "custom",
                            "lifetime"
                        ],
                        "type": "string",
                        "description": "Aggregation period",
                        "name": "period",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start datetime in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End datetime in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "IANA timezone",
                        "name": "timezone",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "none",
                            "previous_period",
                            "previous_year",
                            "lifetime_average"
                        ],
                        "type": "string",
                        "description": "Comparison mode",
                        "name": "compare",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/main.V2SummaryAPIResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/main.APIErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "main.APIErrorBody": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "details": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "main.APIErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "$ref": "#/definitions/main.APIErrorBody"
                }
            }
        },
        "main.V2BatterySummary": {
            "type": "object",
            "properties": {
                "latest_battery_level_percent": {
                    "type": "integer"
                },
                "latest_ideal_range_km": {
                    "type": "number"
                },
                "latest_rated_range_km": {
                    "type": "number"
                }
            }
        },
        "main.V2ChargingSummary": {
            "type": "object",
            "properties": {
                "cost": {
                    "type": "number"
                },
                "duration_min": {
                    "type": "number"
                },
                "energy_added_kwh": {
                    "type": "number"
                },
                "energy_used_kwh": {
                    "type": "number"
                },
                "session_count": {
                    "type": "integer"
                }
            }
        },
        "main.V2ComparisonValue": {
            "type": "object",
            "properties": {
                "current": {
                    "type": "number"
                },
                "delta": {
                    "type": "number"
                },
                "delta_percent": {
                    "type": "number"
                },
                "previous": {
                    "type": "number"
                }
            }
        },
        "main.V2CostSummary": {
            "type": "object",
            "properties": {
                "charging_cost": {
                    "type": "number"
                },
                "cost_per_100km": {
                    "type": "number"
                },
                "cost_per_km": {
                    "type": "number"
                }
            }
        },
        "main.V2DataQuality": {
            "type": "object",
            "properties": {
                "complete": {
                    "type": "boolean"
                },
                "missing_fields": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "sample_count": {
                    "type": "integer"
                },
                "warnings": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "main.V2DrivingAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2DrivingResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2DrivingAnalyticsSummary": {
            "type": "object",
            "properties": {
                "avg_consumption_wh_per_km": {
                    "type": "number"
                },
                "avg_distance_km": {
                    "type": "number"
                },
                "avg_duration_min": {
                    "type": "number"
                },
                "avg_outside_temp_c": {
                    "type": "number"
                },
                "avg_speed_kmh": {
                    "type": "number"
                },
                "battery_level_used_percent": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "drive_count": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "number"
                },
                "estimated_energy_consumed_kwh": {
                    "type": "number"
                },
                "estimated_regenerated_energy_kwh": {
                    "type": "number"
                },
                "max_speed_kmh": {
                    "type": "number"
                },
                "range_loss_km": {
                    "type": "number"
                },
                "total_ascent_m": {
                    "type": "number"
                },
                "total_descent_m": {
                    "type": "number"
                }
            }
        },
        "main.V2DrivingDistributionAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2DrivingDistributionResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2DrivingDistributionItem": {
            "type": "object",
            "properties": {
                "bucket": {
                    "type": "string"
                },
                "distance_km": {
                    "type": "number"
                },
                "drive_count": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "number"
                }
            }
        },
        "main.V2DrivingDistributionResponse": {
            "type": "object",
            "properties": {
                "dimension": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.V2DrivingDistributionItem"
                    }
                }
            }
        },
        "main.V2DrivingRankingAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2DrivingRankingResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2DrivingRankingItem": {
            "type": "object",
            "properties": {
                "distance_km": {
                    "type": "number"
                },
                "drive_id": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "number"
                },
                "end_time": {
                    "type": "string"
                },
                "max_speed_kmh": {
                    "type": "number"
                },
                "metric_unit": {
                    "type": "string"
                },
                "metric_value": {
                    "type": "number"
                },
                "period_start": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "main.V2DrivingRankingResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.V2DrivingRankingItem"
                    }
                },
                "type": {
                    "type": "string"
                }
            }
        },
        "main.V2DrivingResponse": {
            "type": "object",
            "properties": {
                "comparison": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/main.V2ComparisonValue"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/main.V2DrivingAnalyticsSummary"
                }
            }
        },
        "main.V2DrivingSummary": {
            "type": "object",
            "properties": {
                "avg_consumption_wh_per_km": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "drive_count": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "number"
                },
                "max_speed_kmh": {
                    "type": "number"
                }
            }
        },
        "main.V2DrivingTimeseriesAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2DrivingTimeseriesResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2DrivingTimeseriesItem": {
            "type": "object",
            "properties": {
                "avg_consumption_wh_per_km": {
                    "type": "number"
                },
                "avg_speed_kmh": {
                    "type": "number"
                },
                "distance_km": {
                    "type": "number"
                },
                "drive_count": {
                    "type": "integer"
                },
                "duration_min": {
                    "type": "number"
                },
                "estimated_energy_consumed_kwh": {
                    "type": "number"
                },
                "period_start": {
                    "type": "string"
                }
            }
        },
        "main.V2DrivingTimeseriesResponse": {
            "type": "object",
            "properties": {
                "group_by": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/main.V2DrivingTimeseriesItem"
                    }
                }
            }
        },
        "main.V2InfoAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2InfoResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2InfoResponse": {
            "type": "object",
            "properties": {
                "features": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "scope": {
                    "type": "string",
                    "example": "analytics"
                },
                "version": {
                    "type": "string",
                    "example": "v2"
                }
            }
        },
        "main.V2Meta": {
            "type": "object",
            "properties": {
                "car_id": {
                    "type": "integer"
                },
                "compare": {
                    "type": "string"
                },
                "data_quality": {
                    "$ref": "#/definitions/main.V2DataQuality"
                },
                "end": {
                    "type": "string"
                },
                "generated_at": {
                    "type": "string"
                },
                "period": {
                    "type": "string"
                },
                "start": {
                    "type": "string"
                },
                "timezone": {
                    "type": "string"
                },
                "unit": {
                    "$ref": "#/definitions/main.V2Unit"
                }
            }
        },
        "main.V2ParkingSummary": {
            "type": "object",
            "properties": {
                "asleep_duration_min": {
                    "type": "number"
                },
                "offline_duration_min": {
                    "type": "number"
                },
                "online_duration_min": {
                    "type": "number"
                },
                "parked_duration_min": {
                    "type": "number"
                },
                "vampire_drain_percent": {
                    "type": "number"
                }
            }
        },
        "main.V2Summary": {
            "type": "object",
            "properties": {
                "battery": {
                    "$ref": "#/definitions/main.V2BatterySummary"
                },
                "charging": {
                    "$ref": "#/definitions/main.V2ChargingSummary"
                },
                "cost": {
                    "$ref": "#/definitions/main.V2CostSummary"
                },
                "driving": {
                    "$ref": "#/definitions/main.V2DrivingSummary"
                },
                "parking": {
                    "$ref": "#/definitions/main.V2ParkingSummary"
                },
                "updates": {
                    "$ref": "#/definitions/main.V2UpdateSummary"
                }
            }
        },
        "main.V2SummaryAPIResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/main.V2SummaryResponse"
                },
                "meta": {
                    "$ref": "#/definitions/main.V2Meta"
                }
            }
        },
        "main.V2SummaryResponse": {
            "type": "object",
            "properties": {
                "comparison": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/main.V2ComparisonValue"
                    }
                },
                "summary": {
                    "$ref": "#/definitions/main.V2Summary"
                }
            }
        },
        "main.V2Unit": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string",
                    "example": "CNY"
                },
                "distance": {
                    "type": "string",
                    "example": "km"
                },
                "energy": {
                    "type": "string",
                    "example": "kWh"
                },
                "power": {
                    "type": "string",
                    "example": "kW"
                },
                "temperature": {
                    "type": "string",
                    "example": "C"
                }
            }
        },
        "main.V2UpdateSummary": {
            "type": "object",
            "properties": {
                "latest_version": {
                    "type": "string"
                },
                "update_count": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "2.0",
	Host:             "",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "TeslaMateApi",
	Description:      "REST API for TeslaMate data, including V1 resources and V2 objective analytics.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
